default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quasi-case_development

test:
  <<: *default
  database: quasi-case_test

staging:
  <<: *default
  database: quasi-case_staging

production:
  <<: *default
  database: quasi-case_production
  username: quasi-case
  password: <%= ENV['QUASI-CASE_DATABASE_PASSWORD'] %>
